import{A as m,S as c,N as l,K as d,a as u,M as p}from"./assets/vendor-CnDgbuMd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const b=document.querySelector(".navigation__btn"),a=document.querySelector(".navigation__list"),v=document.querySelector(".modal-menu__overlay"),g=document.querySelector(".menu-burger"),_=document.querySelector(".modal-menu__btn-x"),f=r=>{a.contains(r.target)||(a.classList.add("display-none"),document.removeEventListener("click",f))},L=r=>{r.stopPropagation(),a.classList.toggle("display-none")||document.addEventListener("click",f)};b.addEventListener("click",L);g.addEventListener("click",()=>{v.classList.add("open"),document.body.classList.add("no-scroll")});_.addEventListener("click",()=>{v.classList.remove("open"),document.body.classList.remove("no-scroll")});new m(".about-accordion__container",{showMultiple:!0,openOnInit:[0]});new c(".about-swiper",{modules:[l,d,u,p],navigation:{nextEl:".swiper-button-next"},loop:!0,slidesPerView:"auto",keyboard:{enabled:!0,onlyInViewport:!1},a11y:{enabled:!0},mousewheel:{invert:!1}});new c(".projectSwiper",{modules:[l,u,d,p],navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},a11y:{enabled:!0},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!1}});new m(".faq-accordion__container",{showMultiple:!0});const h=document.querySelector(".covers__container"),S=new IntersectionObserver(r=>{r.forEach(t=>{t.isIntersecting?t.target.classList.add("is-active"):t.target.classList.remove("is-active")})},{threshold:0});S.observe(h);new c(".reviewsSwiper",{modules:[l,u,d,p],slidesPerView:"auto",spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},a11y:{enabled:!0},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!1}});const y=document.querySelector(".reviews-swiper__wrapper"),w=()=>{document.querySelector(".reviewsSwiper"),y.innerHTML='<li class="swiper-slide reviews-swiper__message">Not Found</li>'},E=r=>{const t=r.map(n=>{const{author:o,avatar_url:e,review:s}=n;return`
      <li class="swiper-slide reviews-swiper__slide">
          <div class="reviews-swiper__container">
            <img
              class="reviews-swiper__image"
              src="${e}"
              alt="User photo"
            />
            <p class="subtitle reviews-swiper__name">${o}</p>
            <p class="text reviews-swiper__comment">${s}</p>
          </div>
        </li>
      `}).join("");y.innerHTML=t},q=async()=>{try{const t=await(await fetch("https://portfolio-js.b.goit.study/api/reviews")).json();if(t.length>0){E(t);return}w()}catch(r){console.log(r.message),w()}};q();
//# sourceMappingURL=index.js.map
