import{A as E,S as p,N as v,K as w,a as f,M as g,i as S}from"./assets/vendor-CQ71RXvZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();const x=document.querySelector(".navigation__btn"),u=document.querySelector(".navigation__list"),c=document.querySelector(".modal-menu__overlay"),N=document.querySelector(".menu-burger"),k=document.querySelector(".modal-menu__btn-x"),C=t=>{(!u.contains(t.target)||t.target.classList.contains("navigation__link"))&&(u.classList.add("display-none"),document.removeEventListener("click",C))},M=t=>{t.stopPropagation(),u.classList.toggle("display-none")||document.addEventListener("click",C)};x.addEventListener("click",M);const y=()=>{c.classList.remove("open"),document.body.classList.remove("no-scroll"),k.removeEventListener("click",y),c.removeEventListener("click",O)},O=t=>{(t.target.classList.contains("navigation__link")||t.target.classList.contains("modal-cooperation__btn"))&&y()};N.addEventListener("click",()=>{c.classList.add("open"),document.body.classList.add("no-scroll"),c.addEventListener("click",O),k.addEventListener("click",y)});new E(".about-accordion__container",{showMultiple:!0,openOnInit:[0]});new p(".about-swiper",{modules:[v,w,f,g],navigation:{nextEl:".swiper-button-next"},loop:!0,slidesPerView:"auto",keyboard:{enabled:!0,onlyInViewport:!1},a11y:{enabled:!0},mousewheel:{invert:!1}});new p(".projectSwiper",{modules:[v,f,w,g],navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},a11y:{enabled:!0},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!1}});new E(".faq-accordion__container",{showMultiple:!0});const P=document.querySelector(".covers__container"),T=new IntersectionObserver(t=>{t.forEach(e=>{e.isIntersecting?e.target.classList.add("is-active"):e.target.classList.remove("is-active")})},{threshold:0});T.observe(P);new p(".reviewsSwiper",{modules:[v,f,w,g],slidesPerView:"auto",spaceBetween:16,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},a11y:{enabled:!0},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:{invert:!1}});const q=document.querySelector(".reviews-swiper__wrapper"),h=()=>{document.querySelector(".reviewsSwiper"),q.innerHTML='<li class="swiper-slide reviews-swiper__message">Not Found</li>'},V=t=>{const e=t.map(n=>{const{author:a,avatar_url:o,review:s}=n;return`
      <li class="swiper-slide reviews-swiper__slide">
          <div class="reviews-swiper__container">
            <img
              class="reviews-swiper__image"
              src="${o}"
              alt="User photo"
              loading="lazy"
            />
            <p class="subtitle reviews-swiper__name">${a}</p>
            <p class="text reviews-swiper__comment">${s}</p>
          </div>
        </li>
      `}).join("");q.innerHTML=e},I=async()=>{try{const e=await(await fetch("https://portfolio-js.b.goit.study/api/reviews")).json();if(e.length>0){V(e);return}h()}catch(t){console.log(t.message),h()}};I();const i=document.querySelector(".modal-cooperation__overlay"),L=t=>{(t.target===i||t.target.nodeName==="svg"||t.target.nodeName==="button"||t.target.nodeName==="use")&&(i.classList.remove("open"),document.body.classList.remove("no-scroll"),i.removeEventListener("click",L),document.removeEventListener("keydown",_))},_=t=>{t.code==="Escape"&&(i.classList.remove("open"),document.body.classList.remove("no-scroll"),i.removeEventListener("click",L),document.removeEventListener("keydown",_))},j=()=>{i.classList.add("open"),document.body.classList.add("no-scroll"),i.addEventListener("click",L),document.addEventListener("keydown",_)},l=document.querySelector(".work-together-form");let m={userEmail:"",comment:""};const r=document.querySelector(".work-together-form__input-email-indicator"),b=(t,e)=>e.name!=="userEmail"?void 0:t===""?(r.textContent="",r.classList.remove("success","invalid"),e.classList.remove("success","invalid"),!1):/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(t)?(r.classList.remove("invalid"),e.classList.remove("invalid"),r.textContent="Succes!",r.classList.add("success"),e.classList.add("success"),!0):(r.classList.remove("success"),e.classList.remove("success"),r.textContent="Invalid email, try again",r.classList.add("invalid"),e.classList.add("invalid"),!1),B=()=>{const t=D("formCooperation");if(t!==null){const{userEmail:e,comment:n}=l.elements;m=t,e.value=t.userEmail,n.value=t.comment,b(e.value,e)}},A=t=>{const e=t.target;b(e.value,e),m[e.name]=e.value,H("formCooperation",m)},F=async t=>{try{const e=await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(t)});if(!e.ok)throw new Error(`HTTP error! status: ${e.status}`);return await e.json()}catch{return S.error({message:"Oops... Something went wrong, please try again",position:"topRight"}),null}},D=t=>{try{const e=localStorage.getItem(t);return e!==null?JSON.parse(e):null}catch{}},H=(t,e)=>{try{localStorage.setItem(t,JSON.stringify(e))}catch{}},R=async t=>{t.preventDefault();const{userEmail:e,comment:n}=t.currentTarget.elements;if(b(e.value,e)&&n.value.length>0){await F({email:e.value,comment:n.value})!==null&&(j(),l.reset(),r.textContent="",r.classList.remove("success","invalid"),e.classList.remove("success","invalid"),localStorage.removeItem("formCooperation"));return}S.warning({message:"Please fill up all fields!",position:"topRight"})};B();l.addEventListener("submit",R);l.addEventListener("input",A);
//# sourceMappingURL=index.js.map
